// Generated by CoffeeScript 1.6.1
(function() {
  var buidpage, build, conversation, setAndBindPageSizes;

  conversation = [];

  $(document).ready(function() {
    return buidpage();
  });

  buidpage = function() {
    var $convo, message, _i, _len, _results;
    $convo = $(".CONVO");
    _results = [];
    for (_i = 0, _len = conversation.length; _i < _len; _i++) {
      message = conversation[_i];
      _results.push($convo.append(build(message)));
    }
    return _results;
  };

  build = function(message) {
    var $m;
    return $m = $("<div/>", {
      id: "" + message.id,
      "class": "" + message.direction,
      text: "" + message.text
    });
  };

  setAndBindPageSizes = function() {
    return null;
  };

}).call(this);
