// Generated by CoffeeScript 1.6.1
(function() {
  var askWhichFriend, buidConversation, buidpage, conversation, setAndBindPageSizes, transition;

  conversation = [];

  $(document).ready(function() {
    return buidpage();
  });

  buidpage = function() {
    transition();
    return setAndBindPageSizes();
  };

  transition = function() {
    return $("#firstButton").delay(2000).fadeTo(200, 0).delay(200).fadeTo(0, 0, askWhichFriend);
  };

  /*	$(".welcome").removeClass("initial")
  				 .addClass("move")
  				 .delay(1800)
  				 .addClass("second")
  */


  askWhichFriend = function() {
    var buildFriends;
    $("#firstButton").text("Please select a conversation...").delay(1000).fadeTo(300, 1).delay(2000);
    $.get("/allFriends", buildFriends);
    $(".ninja").removeClass("hidden");
    buildFriends = function(Friends) {
      var build, friend, _i, _len, _results;
      console.log(Friends);
      build = function(friend) {
        var $friend, $mostRecent, $name, $pic;
        $friend = $("<div/>", {
          "class": "friend",
          id: "" + friend.name
        });
        $pic = $("<img/>", {
          "class": "friendPIC",
          src: "" + friends.pic_square
        });
        $name = $("<div/>", {
          "class": "friendNAME",
          text: "" + friend.name
        });
        $mostRecent = $("<div/>", {
          "class": "FmostRECENT",
          text: "" + friend.mostRecent
        });
        return $friend.append($pic).append($name).append($mostRecent);
      };
      _results = [];
      for (_i = 0, _len = Friends.length; _i < _len; _i++) {
        friend = Friends[_i];
        _results.push($(".FRIENDS").append(build(friend)));
      }
      return _results;
    };
    return null;
  };

  buidConversation = function() {
    var $convo, build, message, _i, _len;
    $convo = $(".CONVO");
    for (_i = 0, _len = conversation.length; _i < _len; _i++) {
      message = conversation[_i];
      $convo.append(build(message));
    }
    return build = function(message) {
      var $m;
      return $m = $("<div/>", {
        id: "" + message.id,
        "class": "" + message.direction,
        text: "" + message.text
      });
    };
  };

  setAndBindPageSizes = function() {
    var setSizes;
    setSizes = function() {
      var h, w;
      w = $(window).width();
      h = $(window).height();
      return $(".ninja").height(9 * h / 10);
    };
    $(window).bind('resize', function() {
      return setSizes();
    });
    return setSizes();
  };

}).call(this);
