// Generated by CoffeeScript 1.6.3
(function() {
  var isImage;

  isImage = function(url) {
    var request;
    request = require("request");
    return request.head(url, function(error, response) {
      var headers, key, value;
      headers = response.headers;
      for (key in headers) {
        value = headers[key];
        if (key === 'content-type') {
          if (value.slice(0, 5) === 'image') {
            return true;
          }
        }
      }
    });
  };

}).call(this);
