// Generated by CoffeeScript 1.6.1
(function() {
  var validateUrl;

  validateUrl = function(message) {
    var end_occur, finalLinks, first_occur, i, links, request, url, _i, _len;
    request = require("request");
    links = [];
    finalLinks = [];
    first_occur = 0;
    while (true) {
      first_occur = message.indexOf("www", first_occur);
      if (first_occur === -1) {
        break;
      }
      end_occur = message.indexOf(" ", first_occur);
      links.push(message.slice(first_occur, +end_occur + 1 || 9e9));
      first_occur = end_occur;
    }
    first_occur = 0;
    while (true) {
      first_occur = message.indexOf("http", first_occur);
      if (first_occur === -1) {
        break;
      }
      end_occur = message.indexOf(" ", first_occur);
      links.push(message.slice(first_occur, +end_occur + 1 || 9e9));
      first_occur = end_occur;
    }
    for (i = _i = 0, _len = links.length; _i < _len; i = ++_i) {
      url = links[i];
      if (url[0] === "w") {
        links[i] = "http://" + url;
      }
    }
    return links;
  };

}).call(this);
